name: IMDB-Clone

on:
  push:
    branch: 
      - main

jobs:
  build-deploy:
    run-on: windows-latest
    steps:
    #Checkout Repository
      - name: Checkout
        uses: actions/checkout@v6

    #Setup Node
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.16.0

    #Install Dependencies
      - name: Install Dependencies
        run: npm install

    #Build Project
      - name: Build Project
        run: npm run build
    
    #Deploy Project
      - name: Build Project
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist